#!/bin/bash

if test -d /home/$USER/Musique ; then
	dldir=/home/$USER/Musique/
	echo "Le fichier sera enregistrer dans /home/USER/Musique"
	echo $dldir
 else
	dldir=/home/$USER/Musique/
	mkdir $dldir
	echo "Le fichier sera enregistrer dans /home/USER/Musique"
	echo $dldir
fi

youtube-dl -x --output "$dldir%(title)s.%(ext)s" $1 --audio-format mp3 
