#!/bin/bash


#SCRIPT

if test -d /home/$USER/Musique ; then
	dldir=/home/$USER/Musique/
	echo "Le fichier sera enregistrer dans /home/USER/Musique"

elif test -d /home/$USER/Music ; then
	dldir=/home/$USER/Music/
	echo "le fichier sera enregistrer dans /home/USER/Musique"

 else
	dldir=/home/$USER/Musique/
	mkdir $dldir
	echo "Le fichier sera enregistrer dans /home/USER/Musique"

fi

youtube-dl -x --output "$dldir%(title)s.%(ext)s" $1 --audio-format mp3 
